include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    implementation_imports: true
    public_member_api_docs: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    use_setters_to_change_properties: false
    no_default_cases: false
    use_build_context_synchronously: false
    one_member_abstracts: false
    document_ignores: false

formatter:
  trailing_commas: preserve